### ISSUE TITLE
"Her" and "his" should be translated correctly in both of their grammatical roles

### ISSUE THREAD

**Issue by ProfJanetDavis** [glam-lab/degender-the-web#1]
The pronouns "her" and "his" are ambiguous in different ways: 

> "It was her!" -> "It was them!"
> "her book" ->  "their book"
> "his book" -> "their book"
> "That book is his." -> "That book is theirs."

Part of speech tagging is required to resolve these ambiguities. 
<pre>
>>> nltk.pos_tag(nltk.word_tokenize('it was her'))
[('it', 'PRP'), ('was', 'VBD'), ('her', 'PRP')]
>>> nltk.pos_tag(nltk.word_tokenize('her book'))
[('her', 'PRP$'), ('book', 'NN')]
>>> nltk.pos_tag(nltk.word_tokenize('their book'))
[('their', 'PRP$'), ('book', 'NN')]
>>> nltk.pos_tag(nltk.word_tokenize('it was theirs'))
[('it', 'PRP'), ('was', 'VBD'), ('theirs', 'PRP')]
</pre>

**Comment by janetlndavis** [comment]
Andy ran these examples through NLTK for me:

<pre>
>>> nltk.pos_tag(nltk.word_tokenize('it was her'))
[('it', 'PRP'), ('was', 'VBD'), ('her', 'PRP')]
>>> nltk.pos_tag(nltk.word_tokenize('her book'))
[('her', 'PRP$'), ('book', 'NN')]
>>> nltk.pos_tag(nltk.word_tokenize('their book'))
[('their', 'PRP$'), ('book', 'NN')]
>>> nltk.pos_tag(nltk.word_tokenize('it was theirs'))
[('it', 'PRP'), ('was', 'VBD'), ('theirs', 'PRP')]
</pre>

**Comment by janetlndavis** [comment]
May need to revise the lexer to preserve spacing. Argh!

**Comment by janetlndavis** [comment]
The jspos library is not up to the job. The [Stanford POS Tagger](https://nlp.stanford.edu/software/tagger.shtml) appears to be. Someone has written a Node.js module, but is that useful?

**Comment by janetlndavis** [comment]
I could write a Python service using nltk, since that seems to be good enough. Drat, I didn't want a distributed systems problem.

**Comment by ProfJanetDavis** [comment]
Sending information to a server is a very bad idea on all sorts of levels. Brooks suggests looking for a C/C++ POS tagger and compiling to [Web Assembly](https://webassembly.org/).

**Comment by ProfJanetDavis** [comment]
[Compromise](https://github.com/spencermountain/compromise) is good but [does not tag "her" correctly in the noun case](https://github.com/spencermountain/compromise/issues/599). 

It seems like we can distinguish the two cases of "her" and "his" by whether a noun phrase follows the pronoun. This can probably be accomplished through clever use of [match syntax](https://github.com/spencermountain/compromise/wiki/Match-syntax), as Spencer suggests in the issue linked above. The question is whether to just go with this, continuing my dictionary-based strategy, or whether to implement a [compromise plugin](https://nlp-compromise.github.io/compromise-plugin/) specifically for tagging personal pronouns.

Here is the [Compromise API overview](https://observablehq.com/@spencermountain/compromise-api).

**Comment by janetlndavis** [comment]
The [retext English parser](https://github.com/wooorm/parse-english) does not do part-of-speech tagging.

**Comment by janetlndavis** [comment]
To investigate:
https://www.logos.t.u-tokyo.ac.jp/~tsuruoka/lapos/
https://stackoverflow.com/questions/45146099/how-do-i-compile-a-c-file-to-webassembly

**Comment by ProfJanetDavis** [comment]
I'd like to address this before the first developer release because it may require a significant architectural change, along with #8.

**Comment by ProfJanetDavis** [comment]
It seems feasible to distinguish the uses of "her" and "his" as follows:

1. "His" or "her" is a determiner when followed by a noun, adjective, or numeric value (e.g., "his basket", "her green book", "his 99 troubles").
2. "Her" is otherwise a pronoun used as the object of a verb phrase (e.g., "The book that belongs to her is green").
3. "His" is otherwise a possessive noun (e.g., "That basket is his").

I'm becoming more and more inclined to implement a Compromise plug-in.

See also:
* https://www.answers.com/Q/5_example_of_sentences_using_the_pronoun_his
* https://english.stackexchange.com/questions/261843/her-a-determiner-or-a-pronoun 
* [Compromise issue #599, Pronoun use disambiguation](https://github.com/spencermountain/compromise/issues/599).

**Comment by ProfJanetDavis** [comment]
More updates on [Compromise issue #599](https://github.com/spencermountain/compromise/issues/599): Plug-ins are not really a thing. The main developer wants to address the issue in v12, coming soon.

**Comment by ProfJanetDavis** [comment]
Waiting for Compromise v12

**Comment by ProfJanetDavis** [comment]
Let's go ahead and do this now and revisit with Compromise v12
