### ISSUE TITLE
Personal pronoun specifiers are stripped from some pages

### ISSUE THREAD

**Issue by beszel** [glam-lab/degender-the-web#104]
**Describe the bug**
The extension is hiding personal pronoun specifiers like they/them on at least one site.

**To Reproduce**
1. Go to [this page](https://uwm.edu/lgbtrc/qa_faqs/what-are-some-commonly-used-pronouns/)
2. The first sentence seems to say "/hers and /his are a few commonly used pronouns".
3. Click "Restore original content" to see that "she/her" and "he/his" have been hidden.

**Expected behavior**
The page should not be modified when personal pronouns are specified on it.

**Additional context**
"Show highlights" also makes the removed words reappear.

**Comment by ProfJanetDavis** [comment]
I see it! Based on the header, and the results of 'Show changes' I think this is a problem with the CSS formatting. Let me check it out.
