### ISSUE TITLE
Add unit test for `visiblyMentionsGender`

### ISSUE THREAD

**Issue by beszel** [glam-lab/degender-the-web#108]
**Is your feature request related to a problem? Please describe.**
When I added the `visiblyMentionsGender` function (#49), I didn't write a unit test for it.

**Describe the solution you'd like**
 Since all the other methods in `stopword-highlights.js` have unit tests, it seems like this function should have one too.

**Describe alternatives you've considered**
If the function is used internally like a private method, it may be adequately tested via another method; Then it may not need its own unit test. That doesn't seem to be the case here.

**Comment by beszel** [comment]
I don't think I know how to write a unit test for a function that accesses the dom. End-to-end testing might be the right option.

**Comment by ProfJanetDavis** [comment]
If you can't follow a pattern in existing unit tests, then yes, it might be appropriate to write an end-to-end test instead.

Alternatively, consider whether you can extract a function that would be easier to unit test, and move this function to `main.js`.

**Comment by beszel** [comment]
This already has end-to-end tests, but I wasn't sure if unit tests would also be appropriate. It sounds like everything is fine.
