### ISSUE TITLE
This extension needs unit tests

### ISSUE THREAD

**Issue by ProfJanetDavis** [glam-lab/degender-the-web#2]
Use [Jasmine](https://jasmine.github.io/pages/getting_started.html). [Just Not Sorry](https://github.com/janetlndavis/just-not-sorry) might be a good example.

**Comment by ProfJanetDavis** [comment]
It looks like this will involve some significant refactoring for testability.

**Comment by janetlndavis** [comment]
Hmm. Should there be unit tests beyond the end-to-end tests?

**Comment by ProfJanetDavis** [comment]
I would welcome assistance from someone already familiar with unit testing JavaScript.

**Comment by ProfJanetDavis** [comment]
- [x] Create a new branch
- [ ] [Download Jasmine standalone](https://github.com/jasmine/jasmine/releases) and put stuff there
- [ ] Read a [tutorial](https://evanhahn.com/how-do-i-jasmine/)
- [ ] Write tests for `replaceWords`
- [ ] Assess

**Comment by ProfJanetDavis** [comment]
This is [work in progress](https://github.com/glam-lab/degender-the-web/tree/mocha). I decided to use Mocha instead of Jasmine due to [better instructions on running with ES6 modules](https://medium.com/dailyjs/running-mocha-tests-as-native-es6-modules-in-a-browser-882373f2ecb0). See further notes on the [Wiki](https://github.com/glam-lab/degender-the-web/wiki/System-architecture).
