### ISSUE TITLE
There should be an option to disable underlines

### ISSUE THREAD

**Issue by beszel** [glam-lab/degender-the-web#63]
There should be an option to disable the grey dots under replaced pronouns. A checkbox in the plugin options should say "Show grey dots under replaced words" and it can be checked by default. The words may still show their original form on hover.

A plugin options page will need to be created.

Since this project is meant to make the use of the singular "they" feel more natural, it should have this option to draw less attention to the replacement.

**Comment by ProfJanetDavis** [comment]
This is a great idea! I think the transparency of purpose is valuable when first turning the extension on, but maybe this is a bit like training wheels - something to eventually turn off.

See also #5 as that will also require a plugin options page.

**Comment by ProfJanetDavis** [comment]
@irhawk, when disabling underlines, should the mouseover behavior remain?

**Comment by ProfJanetDavis** [comment]
On hold pending #91
