### ISSUE TITLE
Should it not add HTML markup during NLP processing?

### ISSUE THREAD

**Issue by ProfJanetDavis** [glam-lab/degender-the-web#86]
Currently, `replaceProunouns()` adds `span` tags as part of the the replacement text. This approach initially seemed the most straightforward.

However, this means that once a replacement is made, no further NLP processing is possible using the Compromise library. For example, expanded contractions can't be re-contracted, and verb number must be handled before replacing pronouns. Moreover, multi-word phrases can only be marked up word-by-word. (Currently, only pronouns are marked.)

One possibility is to drop the `dgtw-replacement` styling altogether, which would let `replacePronouns()` deal entirely  in plain text. See also #63.

Another possibility is to use a `diff` implementation (such as [this one](https://johnresig.com/projects/javascript-diff-algorithm/)) to compare the original and modified text after the fact. This might also help with #15, since one would have access to both texts together.

**Comment by beszel** [comment]
When I think of how I would use the mouseover feature, I only see myself using it when the extension has made a mistake. If it's made a paragraph less clear, I would want to scroll over a word to see what it was originally and make sense of it.
I would need to use the mouseover feature if the extension is making replacements that reduce readability. If we assume that later releases will perform replacements that are all as readable as the original text, I don't think the mouseover feature is useful. I would rather see improvements to the correctness of replacements, which seem to solve the same problem in a more polished way.

**Comment by ProfJanetDavis** [comment]
If the altered text was that confusing, you might prefer to revert to the original text, even though you would have to find your place again. 

Thanks. This feedback suggests focusing my efforts on those grammar bugs before making a decision here.

**Comment by ProfJanetDavis** [comment]
This would also have the advantage of being able to do the grammar and spelling tests as unit tests, which are faster than e2e tests.

**Comment by ProfJanetDavis** [comment]
On hold pending #91
